---
version: '3'

services:
  climate-control-setup:
    image: climate-control-setup
    build: .
    environment:
      NODE_ENV: production
    ports:
      - 8234:443
    volumes:
      - ~/ssl:/ssl
  climate-control-setup-api:
    image: timmo001/climate-control-setup-api
    environment:
      CERTIFICATES_DIR: /ssl
    ports:
      - 3234:3234
    volumes:
      - ~/ssl:/ssl
